[project]
name = "identiconify"
version = "0.1.0"
description = "Python identicon generator"
requires-python = ">=3.9"
dependencies = [
    "pillow>=11.2.1",
]

[dependency-groups]
dev = [
    "ruff>=0.11.5",
]
